name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


permissions:
  contents: write
  packages: write

# All JOBS------------------------------------------------------------
jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'release'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git configuration
        run: git config user.email "${{ github.actor }}@users.noreply.github.com" && git config user.name "${{ github.actor }}"

      - name: Pull the latest changes from the main branch
        run: git pull origin main --rebase

      - name: Install release-it
        run: npm install -g release-it

      - name: Check if commit message is "Update Readme..."
        id: check_message
        run: |
          LAST_COMMIT=$(git log -1 --pretty=%B)
          if [[ "$LAST_COMMIT" == "Update Readme"* ]]; then
            echo "is_chore_release=true" >> $GITHUB_ENV
          else
            echo "is_chore_release=false" >> $GITHUB_ENV
          fi

      - name: Run release-it
        if: env.is_chore_release == 'true'
        run: npx --yes release-it --ci
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          
